name: flutter_hotel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  google_fonts: ^6.2.1
  provider: ^6.1.4
  font_awesome_flutter: ^10.8.0
  page_transition: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
